const patientPortalUrl =
  "https://accounts.charmtracker.com/signin?hide_signup=true&hide_secure=true&hide_gsignup=true&servicename=charmphr&serviceurl=https%3A%2F%2Fphr2.charmtracker.com%2Fmain.do";

const bookVisitLink = "#book";

const standardSafetyText =
  "TeleDNPnow is for non-emergency medical concerns only. If you have chest pain, severe shortness of breath, stroke symptoms, severe allergic reaction, suicidal thoughts, or any life-threatening symptom, call 911 or go to the nearest emergency room immediately.";

export const teleDnpVisitTypes = [
  { name: "Brief sick visit", price: "$40", keywords: "sick visit quick care cold flu cough sore throat sinus uri uti rash minor illness" },
  { name: "Initial primary care telehealth visit", price: "$60", keywords: "primary care new patient general health chronic care follow up" },
  { name: "Follow-up visit", price: "$40", keywords: "follow up follow-up recheck ongoing care" },
  { name: "Weight loss initial consult", price: "$70", keywords: "weight loss obesity management glp-1 semaglutide tirzepatide lifestyle" },
  { name: "Medication refill visit", price: "$30", keywords: "medication refill prescription refill routine medicine non-controlled" },
];

export const teleDnpWorkingHours = [
  { day: "Sunday", hours: "11:00 AM-6:00 PM" },
  { day: "Monday", hours: "Holiday / Closed" },
  { day: "Tuesday", hours: "Holiday / Closed" },
  { day: "Wednesday", hours: "9:00 AM-6:00 PM" },
  { day: "Thursday", hours: "9:00 AM-6:00 PM" },
  { day: "Friday", hours: "9:00 AM-6:00 PM" },
  { day: "Saturday", hours: "9:00 AM-6:00 PM" },
];

const workingHoursText = teleDnpWorkingHours
  .map((item) => `${item.day}: ${item.hours}`)
  .join("; ");

export const teleDnpServiceParameters = [
  {
    service: "Quick sick visits",
    url: "/quick-sick-visits.html",
    keywords:
      "quick sick visit sick visit same day same-day cough cold flu sinus sore throat allergies rash uti urinary symptoms medication refill nausea diarrhea minor illness urgent concern",
  },
  {
    service: "Primary care",
    url: "/primary_care.html",
    keywords:
      "primary care general health preventive care wellness hypertension diabetes asthma cholesterol medication review fatigue headache dizziness follow up",
  },
  {
    service: "Women's health",
    url: "/Women_health.html",
    keywords:
      "women womens health birth control contraception menstrual period menopause vaginal symptoms yeast infection bv urinary symptoms wellness",
  },
  {
    service: "Chronic care",
    url: "/chronic_care.html",
    keywords:
      "chronic care chronic condition hypertension diabetes high cholesterol asthma thyroid gerd medication monitoring home monitoring",
  },
  {
    service: "Medication refills",
    url: "/medication_refills.html",
    keywords:
      "medication refill prescription refill non-controlled blood pressure diabetes cholesterol asthma inhaler gerd allergy routine refill",
  },
  {
    service: "Lab review",
    url: "/lab_leview.html",
    keywords:
      "lab review results blood work abnormal high low a1c cholesterol thyroid cbc cmp urinalysis imaging report diagnostic test",
  },
  {
    service: "Mental health screening",
    url: "/mental_health_screening.html",
    keywords:
      "mental health screening anxiety stress low mood depression sleep burnout concentration guidance referral 988 crisis",
  },
  {
    service: "Skin and dermatology",
    url: "/skin_dermatology.html",
    keywords:
      "skin dermatology rash acne itching eczema fungal rash ringworm cellulitis skin infection bites redness irritation photo review",
  },
  {
    service: "Sexual health / STI",
    url: "/sexual_health_sti.html",
    keywords:
      "sexual health sti std exposure testing burning discharge itching genital rash partner exposure private confidential",
  },
  {
    service: "Medical weight loss",
    url: "/medical_weight_loss_options.html",
    keywords:
      "medical weight loss obesity management glp-1 semaglutide tirzepatide nutrition lifestyle metabolism bmi weight scale",
  },
];

export const teleDnpQuickAnswers = [
  {
    title: "Shiny Job identity greeting",
    keywords: [
      "shiny",
      "shiny job",
      "hi shiny",
      "hello shiny",
      "np shiny",
      "dr shiny",
      "dr shiny job",
      "how are you shiny",
    ],
    phrases: [
      "shiny",
      "hi shiny",
      "hello shiny",
      "shiny job",
      "np shiny",
      "dr shiny",
      "dr shiny job",
      "how are you shiny",
    ],
    answer:
      "I am Dr. Shiny Job, DNP, FNP-C, a Family Nurse Practitioner.",
    links: [{ label: "About Me", url: "/about_me.html" }],
  },
  {
    title: "Results and next steps",
    keywords: [
      "lab results",
      "x-ray results",
      "xray results",
      "imaging results",
      "test results",
      "result email",
      "email about my result",
      "got an email",
      "schedule for results",
      "what next",
      "follow up results",
    ],
    phrases: [
      "do i get my lab results",
      "do i get my x-ray results",
      "how do i get my lab results",
      "i got one email about my result",
      "do i need to schedule",
      "what next after results",
    ],
    answer:
      "Yes. Lab results, X-ray results, or other test results are usually reviewed through the secure patient portal, by provider follow-up, or by direct communication from TeleDNPnow when appropriate. If you received an email about results, please log in to your CharmHealth/CharmTracker patient portal and check your messages. If you are unsure what to do next, please schedule a follow-up visit or call TeleDNPnow at (480) 626-5571. If the result or symptoms seem urgent or severe, seek urgent care or emergency care right away.",
    links: [
      { label: "Patient Portal", url: patientPortalUrl },
      { label: "Call TeleDNPnow", url: "tel:+14806265571" },
    ],
  },
  {
    title: "Cancel or reschedule",
    keywords: [
      "cancel",
      "cancellation",
      "reschedule",
      "change appointment",
      "move appointment",
      "miss appointment",
      "appointment time",
      "late",
      "no show",
    ],
    phrases: [
      "can i cancel",
      "can i reschedule",
      "how do i reschedule",
      "how do i cancel my appointment",
      "i need to change my appointment",
      "what if i miss my appointment",
    ],
    answer:
      "If you need to cancel or reschedule, please use the CharmHealth/CharmTracker patient portal when available or call TeleDNPnow at (480) 626-5571 as soon as possible. Appointment availability may vary, and missed or late appointments may need to be rescheduled.",
    links: [
      { label: "Patient Portal", url: patientPortalUrl },
      { label: "Call TeleDNPnow", url: "tel:+14806265571" },
    ],
  },
  {
    title: "Identification for visit",
    keywords: [
      "id",
      "identification",
      "drivers license",
      "driver license",
      "photo id",
      "verify identity",
      "proof",
      "patient identity",
    ],
    phrases: [
      "do i need id",
      "do i need identification",
      "do i need photo id",
      "do i need drivers license",
      "how do you verify identity",
    ],
    answer:
      "You may be asked to provide identifying information or a photo ID to help verify your identity before or during a telehealth visit. Please use the secure CharmHealth/CharmTracker patient portal for private documents or call TeleDNPnow if you have questions.",
    links: [{ label: "Patient Portal", url: patientPortalUrl }],
  },
  {
    title: "Home monitoring equipment",
    keywords: [
      "blood pressure machine",
      "bp machine",
      "blood pressure cuff",
      "thermometer",
      "pulse ox",
      "pulse oximeter",
      "oxygen meter",
      "weight scale",
      "scale",
      "glucose monitor",
      "blood sugar monitor",
      "measuring tape",
      "home vitals",
      "vital signs",
    ],
    phrases: [
      "do i need home blood pressure machine",
      "do i need a thermometer",
      "do i need pulse ox",
      "do i need pulse oximeter",
      "do i need weight scale",
      "do i need glucose monitor",
      "what equipment do i need at home",
    ],
    answer:
      "Some telehealth visits are safer and more useful when you have home measurements available. Depending on your concern, the provider may ask for blood pressure, heart rate, temperature, oxygen level, weight, blood sugar, or waist measurement. You do not always need all equipment, but chronic care, breathing concerns, diabetes, blood pressure follow-up, and weight management may require home monitoring.",
  },
  {
    title: "Upload reports and documents",
    keywords: [
      "upload lab report",
      "upload labs",
      "upload xray",
      "upload x-ray",
      "upload imaging",
      "upload report",
      "send lab report",
      "send document",
      "medical records",
      "prior results",
      "outside records",
    ],
    phrases: [
      "can i upload lab reports",
      "can i upload x-ray report",
      "can i send medical records",
      "can i send my lab report",
      "can i upload documents",
    ],
    answer:
      "Yes, you may be able to upload or share lab reports, imaging reports, medication lists, photos, or other documents through the secure CharmHealth/CharmTracker patient portal when available. Please do not place private medical documents in the public website chat.",
    links: [{ label: "Patient Portal", url: patientPortalUrl }],
  },
  {
    title: "Antibiotics",
    keywords: [
      "antibiotic",
      "antibiotics",
      "infection",
      "amoxicillin",
      "z pack",
      "zpak",
      "azithromycin",
      "doxycycline",
      "uti antibiotic",
      "sinus antibiotic",
      "strep antibiotic",
    ],
    phrases: [
      "can i get antibiotics",
      "do you prescribe antibiotics",
      "can i get antibiotic for infection",
      "can i get antibiotic for sinus",
      "can i get antibiotic for uti",
    ],
    answer:
      "Antibiotics may be prescribed only when clinically appropriate and safe after provider evaluation. Many symptoms are viral or may need testing before antibiotics are recommended. The provider will review symptoms, allergies, medical history, pregnancy status when relevant, and safety concerns before deciding on treatment.",
    links: [{ label: "Antibiotics Article", url: "/article/antibiotics.html" }],
  },
  {
    title: "Work or school note",
    keywords: [
      "work note",
      "school note",
      "excuse note",
      "doctor note",
      "return to work",
      "return to school",
      "letter",
      "medical note",
    ],
    phrases: [
      "can i get work note",
      "can i get school note",
      "can i get a doctor note",
      "can i get excuse note",
      "can i get return to work note",
    ],
    answer:
      "A work or school note may be provided when clinically appropriate after a completed visit. Notes depend on the provider's assessment, the reason for the visit, and what can safely be supported through telehealth.",
  },
  {
    title: "Specialist referral",
    keywords: [
      "referral",
      "specialist",
      "specialty",
      "dermatology referral",
      "cardiology referral",
      "gi referral",
      "obgyn referral",
      "ob/gyn referral",
      "urology referral",
      "pulmonology referral",
    ],
    phrases: [
      "can i get referral to specialist",
      "do you give specialist referral",
      "can you refer me to dermatologist",
      "can you refer me to cardiology",
      "can you refer me to obgyn",
    ],
    answer:
      "A specialist referral may be recommended or provided when clinically appropriate. Some concerns require in-person evaluation, labs, imaging, or urgent care before referral decisions can be made. Referral options may also depend on insurance, network rules, and local availability.",
  },
  {
    title: "Pregnancy-related care limits",
    keywords: [
      "pregnant",
      "pregnancy",
      "expecting",
      "ob",
      "obgyn",
      "ob/gyn",
      "prenatal",
      "miscarriage",
      "vaginal bleeding pregnancy",
      "pelvic pain pregnancy",
    ],
    phrases: [
      "do you treat pregnancy",
      "can i be seen if pregnant",
      "i am pregnant",
      "pregnancy symptoms",
      "pregnancy concern",
    ],
    answer:
      "Pregnancy-related symptoms may need OB/GYN or in-person evaluation. TeleDNPnow is not a substitute for prenatal care, labor and delivery care, or emergency pregnancy evaluation. If you are pregnant and have vaginal bleeding, severe abdominal or pelvic pain, fainting, severe vomiting/dehydration, severe headache, vision changes, chest pain, shortness of breath, or decreased fetal movement, call 911, contact your OB provider, or go to the emergency room.",
  },
  {
    title: "Infants and young children",
    keywords: [
      "infant",
      "newborn",
      "baby under 6 months",
      "baby under six months",
      "young infant",
      "fever infant",
      "pediatric emergency",
    ],
    phrases: [
      "do you treat infants",
      "do you see newborns",
      "do you see baby under 6 months",
      "do you see infants under 6 months",
      "my baby has fever",
    ],
    answer:
      "TeleDNPnow may see children older than 6 months for certain non-emergency concerns when appropriate. Newborns or infants younger than 6 months, especially with fever, breathing trouble, poor feeding, dehydration, unusual sleepiness, injury, or serious symptoms, should be evaluated urgently by an in-person pediatric provider, urgent care, or emergency room.",
  },
  {
    title: "Severe pain limits",
    keywords: [
      "severe pain",
      "worst pain",
      "unbearable pain",
      "severe headache",
      "severe back pain",
      "severe pelvic pain",
      "severe chest pain",
      "severe stomach pain",
      "10 out of 10 pain",
    ],
    phrases: [
      "do you treat severe pain",
      "i have severe pain",
      "my pain is unbearable",
      "i have 10 out of 10 pain",
    ],
    answer:
      "Severe, sudden, worsening, or unbearable pain may require urgent in-person evaluation, imaging, labs, or emergency care. TeleDNPnow does not prescribe narcotic pain medications or chronic opioid therapy. If pain is severe or associated with chest pain, weakness, fainting, severe abdominal pain, injury, fever, confusion, or shortness of breath, call 911 or go to the emergency room.",
  },
  {
    title: "Dental pain",
    keywords: [
      "dental",
      "tooth",
      "toothache",
      "gum",
      "mouth pain",
      "dental abscess",
      "broken tooth",
      "jaw swelling",
    ],
    phrases: [
      "do you treat dental pain",
      "can you help with tooth pain",
      "i have toothache",
      "i have dental abscess",
    ],
    answer:
      "Dental pain usually requires evaluation by a dentist or urgent dental clinic. TeleDNPnow may provide general guidance for non-emergency concerns, but tooth infections, broken teeth, dental abscesses, jaw swelling, facial swelling, fever, trouble swallowing, or trouble breathing need urgent dental or emergency evaluation.",
  },
  {
    title: "Eye problems",
    keywords: [
      "eye",
      "eyes",
      "pink eye",
      "conjunctivitis",
      "eye redness",
      "eye pain",
      "vision change",
      "vision loss",
      "blurry vision",
      "contact lens",
      "eye injury",
    ],
    phrases: [
      "do you treat eye problems",
      "can you treat pink eye",
      "i have eye pain",
      "i have vision changes",
      "i lost vision",
    ],
    answer:
      "Some mild eye concerns, such as possible pink eye, may be reviewed by telehealth when appropriate. Eye pain, vision loss, sudden blurry vision, eye injury, severe light sensitivity, contact lens-related infection concern, or one-sided vision changes require urgent in-person eye care or emergency evaluation.",
  },
  {
    title: "COVID and flu",
    keywords: [
      "covid",
      "covid-19",
      "coronavirus",
      "flu",
      "influenza",
      "paxlovid",
      "tamiflu",
      "antiviral",
      "fever cough",
      "body aches",
    ],
    phrases: [
      "do you treat covid",
      "do you treat flu",
      "can i get paxlovid",
      "can i get tamiflu",
      "i have covid symptoms",
      "i have flu symptoms",
    ],
    answer:
      "TeleDNPnow may help with non-emergency COVID or flu-like symptoms when clinically appropriate, including symptom review, testing guidance, and antiviral discussion for eligible patients. Treatment depends on timing, risk factors, medications, kidney/liver history, test results, and provider assessment. Severe shortness of breath, chest pain, confusion, blue lips, dehydration, or worsening symptoms require urgent or emergency care.",
    links: [
      { label: "COVID-19 Article", url: "/article/COVID_19.html" },
      { label: "Cold and Flu Article", url: "/article/cold_flu.html" },
    ],
  },
  {
    title: "UTI symptoms",
    keywords: [
      "uti",
      "urinary tract infection",
      "urine infection",
      "burning urination",
      "painful urination",
      "urinary frequency",
      "urinary urgency",
      "bladder infection",
      "blood in urine",
      "flank pain",
    ],
    phrases: [
      "do you treat uti",
      "can you treat uti symptoms",
      "i have uti symptoms",
      "i have burning urination",
      "can i get uti antibiotic",
    ],
    answer:
      "TeleDNPnow may evaluate appropriate UTI symptoms by telehealth for Arizona patients. Testing or labs may be recommended, and treatment depends on symptoms, pregnancy status, allergies, kidney symptoms, fever, medical history, and provider assessment. Fever, flank/back pain, vomiting, pregnancy, blood in urine, severe pain, or recurrent/complicated symptoms may require urgent in-person evaluation.",
    links: [{ label: "UTI Article", url: "/article/urinary_tract_infections.html" }],
  },
  {
    title: "STI and STD exposure",
    keywords: [
      "sti",
      "std",
      "sexually transmitted",
      "exposure",
      "chlamydia",
      "gonorrhea",
      "trichomonas",
      "herpes",
      "genital rash",
      "genital bumps",
      "discharge",
      "burning",
      "partner exposure",
    ],
    phrases: [
      "do you treat std exposure",
      "do you treat sti exposure",
      "i was exposed to std",
      "can i get std testing",
      "can i get sti testing",
      "can you help with sexual health",
    ],
    answer:
      "TeleDNPnow may help with confidential sexual health/STI concerns when clinically appropriate, including risk discussion, testing recommendations, lab orders, result review, and treatment guidance. Some symptoms require in-person exam, specimen collection, OB/GYN, urology, urgent care, or emergency evaluation.",
    links: [{ label: "Sexual Health / STI", url: "/sexual_health_sti.html" }],
  },
  {
    title: "Phone-only visits",
    keywords: [
      "phone only",
      "telephone visit",
      "phone visit",
      "no video",
      "dont have video",
      "don't have video",
      "no cell phone",
      "dont have cell phone",
      "don't have cell phone",
      "talk over phone",
      "call only",
    ],
    phrases: [
      "can i talk to the provider over the phone only",
      "i dont have a cell phone for video visit",
      "i don't have a cell phone for video visit",
      "can i do phone only",
      "can i have a telephone visit",
    ],
    answer:
      "Phone-only visits may be possible for some non-emergency concerns, depending on the reason for the visit and provider judgment. Some conditions are safer with video, photos, home vital signs, labs, or in-person evaluation. If you do not have a phone for video visits, please call TeleDNPnow at (480) 626-5571 before scheduling so the best visit option can be reviewed.",
    links: [{ label: "Call TeleDNPnow", url: "tel:+14806265571" }],
  },
  {
    title: "Rash photo upload",
    keywords: [
      "rash picture",
      "rash photo",
      "send picture",
      "send photo",
      "upload picture",
      "upload photo",
      "skin photo",
      "skin picture",
      "photo review",
    ],
    phrases: [
      "can i send a rash picture",
      "can i send rash photo",
      "can i upload a skin picture",
      "can i send a picture of my rash",
    ],
    answer:
      "Yes. For some skin concerns, clear photos may help the provider review the rash or skin change during a telehealth visit. Photos should be sent through the secure CharmHealth/CharmTracker patient portal when available, not through public website chat. Some rashes or skin problems still require in-person evaluation, testing, urgent care, or dermatology referral.",
    links: [
      { label: "Patient Portal", url: patientPortalUrl },
      { label: "Skin and Dermatology", url: "/skin_dermatology.html" },
    ],
  },
  {
    title: "Follow-up timing",
    keywords: [
      "how often",
      "come back",
      "follow up",
      "follow-up",
      "next visit",
      "how many visits",
      "need to come",
      "recheck",
    ],
    phrases: [
      "how often do i need to come",
      "how often do i need follow up",
      "when do i come back",
      "when is my next visit",
    ],
    answer:
      "Follow-up timing depends on your condition, symptoms, medications, test results, and provider assessment. Some concerns may need a short follow-up in a few days, routine follow-up in a few weeks or months, or urgent in-person care if symptoms worsen. Your provider will recommend the follow-up plan that is safest for your situation.",
  },
  {
    title: "Payment limits and no insurance",
    keywords: [
      "no insurance",
      "dont have insurance",
      "don't have insurance",
      "uninsured",
      "no money",
      "dont have money",
      "don't have money",
      "cannot pay",
      "can't pay",
      "zelle",
      "cash",
      "pay cash",
      "payment method",
      "credit card",
      "debit card",
    ],
    phrases: [
      "i dont have insurance",
      "i don't have insurance",
      "i dont have money now",
      "i don't have money now",
      "do i pay zelle",
      "do i pay cash",
      "can i pay with zelle",
      "can i pay cash",
    ],
    answer:
      "No insurance? No worries. TeleDNPnow offers transparent self-pay options for eligible telehealth visits. Payment is usually handled securely by card through the approved payment process. TeleDNPnow does not collect full card numbers in the public website chat. Please call (480) 626-5571 if you have a payment concern before scheduling. Zelle or cash payment options are not handled through the website chat.",
    links: [{ label: "Call TeleDNPnow", url: "tel:+14806265571" }],
  },
  {
    title: "Worsening symptoms",
    keywords: [
      "worsened",
      "worse",
      "getting worse",
      "symptoms worsened",
      "not better",
      "getting sicker",
      "worsening symptoms",
      "severe symptoms",
    ],
    phrases: [
      "what if my symptoms worsened",
      "what if my symptoms get worse",
      "my symptoms are getting worse",
      "i am getting worse",
    ],
    answer:
      "If your symptoms are worsening, please seek the right level of care right away. If you have chest pain, severe shortness of breath, stroke symptoms, severe abdominal pain, fainting, confusion, severe allergic reaction, uncontrolled bleeding, suicidal thoughts, or any life-threatening symptom, call 911 or go to the nearest emergency room. For non-emergency worsening symptoms, contact TeleDNPnow or schedule a follow-up visit.",
    links: [{ label: "Call TeleDNPnow", url: "tel:+14806265571" }],
  },
  {
    title: "Referral bonus",
    keywords: [
      "referral bonus",
      "refer a friend",
      "bonus",
      "discount for referral",
      "referral discount",
      "reward",
      "rewards",
    ],
    phrases: [
      "do i get referral bonus",
      "do you have referral bonus",
      "do i get a discount for referral",
      "can i refer a friend",
    ],
    answer:
      "TeleDNPnow does not currently advertise a referral bonus through the website chat. If a promotion or referral program becomes available, details would need to be confirmed directly with the facility. Please call (480) 626-5571 or email care@telednpnow.org for current information.",
    links: [
      { label: "Call TeleDNPnow", url: "tel:+14806265571" },
      { label: "Email TeleDNPnow", url: "mailto:care@telednpnow.org" },
    ],
  },
  {
    title: "Children and pediatric visits",
    keywords: [
      "kids",
      "children",
      "child",
      "baby",
      "infant",
      "pediatric",
      "pediatrics",
      "6 months",
      "six months",
      "minor",
      "teen",
      "teenager",
    ],
    phrases: [
      "do you see kids",
      "do you see children",
      "do you see babies",
      "kids older than 6 months",
      "do you see kids older than 6 months",
    ],
    answer:
      "TeleDNPnow may see children older than 6 months for certain non-emergency telehealth concerns when clinically appropriate. Pediatric care depends on the child's age, symptoms, medical history, available information, and provider assessment. Emergency symptoms, breathing trouble, dehydration, severe pain, high fever in young infants, injury, or serious illness require urgent in-person care or emergency evaluation.",
  },
  {
    title: "How are you",
    keywords: [
      "how are you",
      "how r you",
      "how are u",
      "how you doing",
      "how are you doing",
      "are you ok",
      "are you okay",
    ],
    phrases: [
      "how are you",
      "how r you",
      "how are u",
      "how are you doing",
      "how you doing",
    ],
    answer:
      "I am doing good, thanks for asking. Welcome to TeleDNPnow. How can I help you?",
  },
  {
    title: "In-person and home visits",
    keywords: [
      "in person",
      "in-person",
      "come in person",
      "office visit",
      "clinic visit",
      "walk in",
      "walk-in",
      "home visit",
      "home visits",
      "house call",
      "house calls",
      "come to my home",
      "come to house",
      "at home visit",
    ],
    phrases: [
      "can i come inperson",
      "can i come in person",
      "do you have in person visits",
      "can you do home visits",
      "do you do home visits",
      "can you come to my house",
      "do you do house calls",
    ],
    answer:
      "At present, TeleDNPnow is a telehealth practice only. TeleDNPnow does not currently offer in-person office visits, walk-in visits, home visits, or house calls. If your condition requires a physical exam, hands-on treatment, imaging, urgent testing, or emergency care, you may be advised to seek in-person care.",
  },
  {
    title: "Coffee and caffeine",
    keywords: [
      "coffee",
      "caffeine",
      "tea",
      "energy drink",
      "espresso",
      "latte",
      "is coffee ok",
      "can i drink coffee",
      "coffee okay",
      "caffeine okay",
    ],
    phrases: [
      "is coffee ok",
      "is coffee okay",
      "can i drink coffee",
      "can i have caffeine",
      "is caffeine ok",
      "is caffeine okay",
    ],
    answer:
      "For many people, moderate coffee or caffeine may be okay, but it depends on your health history, symptoms, medications, and reason for the visit. Caffeine may worsen anxiety, palpitations, insomnia, reflux/heartburn, high blood pressure, dehydration, and some pregnancy-related concerns. If you have chest pain, severe palpitations, fainting, severe shortness of breath, or any emergency symptoms, call 911 or go to the ER. For personalized advice, please discuss caffeine use during your TeleDNPnow visit.",
  },
  {
    title: "Lab orders",
    keywords: [
      "lab order",
      "lab orders",
      "labs",
      "laboratory",
      "blood work",
      "bloodwork",
      "urine test",
      "urinalysis",
      "testing",
      "test order",
      "quest",
      "labcorp",
      "lab corp",
      "sonora quest",
      "sonara quest",
      "my lab",
      "local lab",
      "diagnostic test",
    ],
    phrases: [
      "do i get lab orders in my lab",
      "can i get lab orders",
      "can you order labs",
      "can you send lab order to my lab",
      "do you order blood work",
      "can i use my local lab",
    ],
    answer:
      "Lab orders may be provided when clinically appropriate after a TeleDNPnow visit. TeleDNPnow is integrated with major labs, including Labcorp and Sonora Quest. The provider will review your symptoms, health history, current medications, and clinical needs, then determine whether labs are needed and where they can be completed. Some concerns may require in-person evaluation, urgent care, imaging, or specialist referral instead of, or in addition to, lab testing.",
    links: [{ label: "Lab Review", url: "/lab_leview.html" }],
  },
  {
    title: "Skin and dermatology concerns",
    keywords: [
      "acne",
      "lesion",
      "skin lesion",
      "rash",
      "pimple",
      "pimples",
      "pustule",
      "pustules",
      "papule",
      "papules",
      "white head",
      "whitehead",
      "whiteheads",
      "blackhead",
      "blackheads",
      "comedone",
      "comedones",
      "folliculitis",
      "dermatitis",
      "eczema",
      "dry skin",
      "dandruff",
      "itchy skin",
      "itching",
      "skin infection",
      "ringworm",
      "boil",
      "cellulitis",
    ],
    phrases: [
      "do you treat acne",
      "do you treat rash",
      "do you treat eczema",
      "do you treat folliculitis",
      "do you treat dermatitis",
      "do you treat dandruff",
      "can you help with itchy skin",
      "can you help with pimples",
      "can you help with blackheads",
      "can you help with whiteheads",
    ],
    answer:
      "Skin and dermatology telehealth visits are available at TeleDNPnow when clinically appropriate. Common concerns may include acne, lesions, rashes, pimples, pustules, papules, whiteheads, blackheads, comedones, folliculitis, dermatitis, eczema, dry skin, dandruff, and itchy skin. Some skin problems may require clear photos, labs, culture, in-person exam, urgent care, or dermatology referral depending on severity and safety.",
    links: [{ label: "Skin and Dermatology", url: "/skin_dermatology.html" }],
  },
  {
    title: "Prescriptions to pharmacy",
    keywords: [
      "prescription",
      "prescriptions",
      "pharmacy",
      "send prescription",
      "my pharmacy",
      "rx",
      "medication",
      "medications",
      "refill",
      "refills",
      "preferred pharmacy",
      "walgreens",
      "cvs",
      "walmart pharmacy",
    ],
    phrases: [
      "can i get prescription in my pharmacy",
      "can i get a prescription sent to my pharmacy",
      "do you send prescription to pharmacy",
      "can you send medicine to my pharmacy",
      "can you send medication to walgreens",
      "can you send medication to cvs",
    ],
    answer:
      "Yes. When clinically appropriate and safe, TeleDNPnow may send prescriptions or eligible medication refills to your preferred pharmacy. Prescription decisions depend on your health history, symptoms, allergies, current medications, diagnosis, state rules, and provider assessment. TeleDNPnow does not prescribe narcotic pain medications, controlled substances, chronic opioid therapy, ADHD stimulants, or certain behavioral health medications through telehealth.",
    links: [{ label: "Medication Refills", url: "/medication_refills.html" }],
  },
  {
    title: "Immunizations and vaccines",
    keywords: [
      "immunization",
      "immunizations",
      "vaccine",
      "vaccines",
      "vaccination",
      "flu shot",
      "influenza shot",
      "pneumonia shot",
      "pneumococcal",
      "covid shot",
      "covid vaccine",
      "covid booster",
      "shingles shot",
      "shingles vaccine",
      "tdap",
      "tetanus",
    ],
    phrases: [
      "do you give immunizations",
      "do you give vaccines",
      "do you offer flu shot",
      "do you offer pneumonia shot",
      "do you offer covid shot",
      "do you offer shingles shot",
      "can i get a vaccine",
    ],
    answer:
      "Immunizations and vaccines such as flu shots, pneumonia shots, COVID vaccines or boosters, shingles vaccines, tetanus/Tdap, and other injections require in-person vaccination services. At present, TeleDNPnow is a telehealth practice only and does not administer vaccines through the website or virtual visits. Please contact a local pharmacy, primary care clinic, health department, or in-person vaccination site.",
  },
  {
    title: "Mental health screening scope",
    keywords: [
      "anxiety",
      "anxious",
      "stress",
      "stressed",
      "adhd",
      "add",
      "mental health",
      "depression",
      "depressed",
      "panic",
      "panic attack",
      "burnout",
      "overwhelmed",
      "sleep",
      "insomnia",
      "emotional",
      "psychiatric",
      "therapy",
      "counseling",
    ],
    phrases: [
      "i have anxiety",
      "i feel anxious",
      "i am stressed",
      "i have stress",
      "do you treat adhd",
      "do you treat mental health",
      "can you help with anxiety",
      "can you help with stress",
      "can you help with depression",
      "can you help with panic attacks",
    ],
    answer:
      "TeleDNPnow may provide telehealth screening, education, and guidance for minor mental health concerns such as stress, anxiety symptoms, burnout, sleep concerns, or feeling overwhelmed. TeleDNPnow does not provide emergency mental health care, long-term psychiatric management, ADHD stimulant treatment, controlled substances, or crisis services. If symptoms are serious, worsening, involve safety concerns, suicidal thoughts, self-harm, psychosis, severe depression, or a mental health crisis, please call 911, go to the nearest emergency room, contact local mental health services, or call/text 988 for the Suicide & Crisis Lifeline.",
    links: [{ label: "Mental Health Screening", url: "/mental_health_screening.html" }],
  },
  {
    title: "Emergency symptoms",
    keywords: [
      "chest pain",
      "severe abdominal pain",
      "vision loss",
      "loss of vision",
      "severe vomiting",
      "pregnant emergency",
      "pregnancy emergency",
      "emergency",
      "er",
      "emergency room",
      "911",
      "stroke",
      "severe shortness of breath",
      "fainting",
      "uncontrolled bleeding",
      "severe allergic reaction",
      "suicidal",
      "life threatening",
      "life-threatening",
    ],
    phrases: [
      "i am having chest pain",
      "i have chest pain",
      "i have severe abdominal pain",
      "i am having severe abdominal pain",
      "i have vision loss",
      "i lost vision",
      "i have severe vomiting",
      "i am pregnant and have emergency symptoms",
      "i am having an emergency",
    ],
    answer:
      "These symptoms may be an emergency. Telehealth is not appropriate for chest pain, severe abdominal pain, vision loss, severe vomiting, pregnancy-related emergency symptoms, stroke symptoms, severe shortness of breath, fainting, uncontrolled bleeding, severe allergic reaction, suicidal thoughts, or any life-threatening condition. Please call 911 or go to the nearest emergency room immediately.",
  },
  {
    title: "Offensive language",
    keywords: [
      "fuck",
      "fucking",
      "bastard",
      "shit",
      "asshole",
      "bitch",
      "stupid",
      "idiot",
      "damn",
      "hate you",
    ],
    phrases: [
      "fuck",
      "bastard",
      "fuck you",
      "you bastard",
    ],
    answer:
      "I am afraid to answer messages with offensive or abusive language. Please ask your question again in respectful wording, and I will do my best to help.",
  },
  {
    title: "Greeting",
    keywords: [
      "hi",
      "hello",
      "hey",
      "help",
      "start",
      "question",
      "questions",
      "info",
      "information",
      "support",
      "good morning",
      "good afternoon",
      "good evening",
      "thanks",
      "thank you",
      "ok",
      "okay",
      "yes",
      "no",
    ],
    phrases: [
      "hi",
      "hello",
      "hey",
      "good morning",
      "good afternoon",
      "good evening",
      "can you help",
      "i need help",
      "need help",
      "help me",
      "what can you do",
      "what do you do",
      "tell me more",
      "more information",
      "i have a question",
      "i want to ask a question",
      "thank you",
      "thanks",
    ],
    answer:
      "Hi, welcome to TeleDNPnow. I can help with services, self-pay prices, booking, the patient portal, contact information, and general website articles. Please do not enter private medical details here.",
    links: [
      { label: "Book Visit", url: bookVisitLink },
      { label: "Patient Portal Login", url: patientPortalUrl },
    ],
  },
  {
    title: "Company identity",
    keywords: [
      "company",
      "business",
      "practice",
      "clinic",
      "tele dnp",
      "telednp",
      "telednpnow",
      "telehealth",
      "telemedicine",
      "np",
      "nurse practitioner",
      "family practice",
      "family medicine",
      "primary care",
      "virtual clinic",
      "online clinic",
      "arizona clinic",
    ],
    phrases: [
      "what company is telednpnow",
      "what is telednpnow",
      "what is tele dnp",
      "what does telednpnow do",
      "is telednpnow telehealth",
      "is this a family practice",
      "is this a nurse practitioner practice",
      "telehealth np family practice",
    ],
    answer:
      "TeleDNPnow is a telehealth family practice-style service for Arizona patients. It is led by Shiny Job, DNP, FNP-C, a board-certified Family Nurse Practitioner. TeleDNPnow provides convenient virtual care for non-emergency concerns, primary care follow-up, medication refills when appropriate, women's health, men's health concerns, chronic care support, skin concerns, lab review, and medical weight loss management.",
    links: [
      { label: "About Me", url: "/about_me.html" },
      { label: "Services", url: "#services" },
    ],
  },
  {
    title: "Book a telehealth visit",
    keywords: [
      "book",
      "booking",
      "schedule",
      "appointment",
      "calendar",
      "visit",
      "same day",
      "same-day",
      "today",
      "available",
      "availability",
      "open appointment",
      "make appointment",
      "set appointment",
      "reserve",
      "tele visit",
      "televisit",
      "virtual visit",
      "see provider",
      "see doctor",
      "see nurse practitioner",
      "need visit",
      "want appointment",
      "open calendar",
      "calendar not opening",
      "book now",
      "booking link",
    ],
    phrases: [
      "how do i book",
      "how can i schedule",
      "book a visit",
      "schedule a visit",
      "same day appointment",
      "need appointment today",
      "i need a visit",
      "i want to see the provider",
      "how soon can i be seen",
      "can i be seen today",
      "open the calendar",
    ],
    answer:
      "You can book a TeleDNPnow telehealth visit online using the Book Visit button. TeleDNPnow offers convenient virtual visits for Arizona patients for non-emergency concerns.",
    links: [{ label: "Book Visit", url: bookVisitLink }],
  },
  {
    title: "Patient portal",
    keywords: [
      "portal",
      "patient portal",
      "register",
      "registration",
      "login",
      "sign in",
      "signin",
      "charm",
      "charmhealth",
      "charm health",
      "charmtracker",
      "charm tracker",
      "phr",
      "ehr",
      "forms",
      "intake",
      "questionnaire",
      "secure message",
      "patient account",
      "account",
      "password",
      "forgot password",
      "reset password",
      "new patient",
      "existing patient",
      "sign up",
      "signup",
      "paperwork",
      "pre appointment",
      "pre-appointment",
      "questionnaires",
    ],
    phrases: [
      "where do i login",
      "how do i register",
      "patient portal login",
      "charmhealth login",
      "fill intake form",
      "complete forms",
      "i need to login",
      "where is the portal",
      "how do i fill forms",
      "new patient registration",
    ],
    answer:
      "TeleDNPnow uses CharmHealth/CharmTracker as the secure EHR patient portal for registration, visit information, forms, and patient communication.",
    links: [
      {
        label: "Patient Portal Login",
        url: patientPortalUrl,
      },
    ],
  },
  {
    title: "In-person and aesthetic services",
    keywords: [
      "iv therapy",
      "iv hydration",
      "facial massage",
      "massage",
      "trigger point",
      "trigger point injection",
      "injection",
      "natural therapy",
      "natural treatment",
      "aesthetic",
      "aesthetic treatment",
      "botox",
      "filler",
      "facial",
      "skin treatment",
      "in person",
      "in-person",
      "office visit",
    ],
    phrases: [
      "do you offer iv therapy",
      "do you offer facial massage",
      "do you offer trigger point injection",
      "do you offer natural therapy",
      "do you offer aesthetic treatment",
      "do you do botox",
      "do you do fillers",
      "do you have in person visits",
    ],
    answer:
      "At present, TeleDNPnow is a telehealth practice only and does not offer IV therapy, facial massage, trigger point injections, natural therapy procedures, Botox, fillers, or aesthetic treatments. These services may be considered in the future if in-person visits become available.",
  },
  {
    title: "Payment questions and unresolved visits",
    keywords: [
      "refund",
      "reimburse",
      "reimbursement",
      "money back",
      "return money",
      "payment issue",
      "billing issue",
      "hospital",
      "go to hospital",
      "went to hospital",
      "not resolved",
      "not better",
      "service not resolved",
      "did not help",
      "unsatisfied",
    ],
    phrases: [
      "do you reimburse money",
      "do you refund money",
      "do i get money back",
      "what if i have to go to hospital",
      "what if my problem is not resolved",
      "what if service is not resolved",
      "what if i am not better",
    ],
    answer:
      "If you have a billing question, payment concern, or your symptoms were not resolved after a TeleDNPnow visit, please contact the facility directly so your concern can be reviewed properly. You may call (480) 626-5571 or email care@telednpnow.org. If you are advised to go to the hospital, urgent care, or emergency room, please follow that medical guidance right away. Telehealth has limitations, and some conditions require in-person evaluation, testing, imaging, or emergency care.",
    links: [
      { label: "Call TeleDNPnow", url: "tel:+14806265571" },
      { label: "Email TeleDNPnow", url: "mailto:care@telednpnow.org" },
    ],
  },
  {
    title: "Trust and legitimacy",
    keywords: [
      "fraud",
      "scam",
      "fake",
      "legit",
      "legitimate",
      "real company",
      "real practice",
      "trust",
      "trusted",
      "verify",
      "safe",
      "is this real",
    ],
    phrases: [
      "is this company fraud",
      "is telednpnow fraud",
      "is this a scam",
      "is telednpnow a scam",
      "is this company legit",
      "is telednpnow legit",
      "is this real",
      "can i trust telednpnow",
    ],
    answer:
      "TeleDNPnow is a telehealth practice founded by Shiny Job, DNP, FNP-C, a licensed, board-certified Family Nurse Practitioner. TeleDNPnow uses CharmHealth/CharmTracker as the secure EHR patient portal for registration, visit information, and patient communication. If you have any concern or would like to verify details before scheduling, please call (480) 626-5571 or email care@telednpnow.org.",
    links: [
      { label: "About TeleDNPnow", url: "/about_me.html" },
      { label: "Patient Portal", url: patientPortalUrl },
      { label: "Call TeleDNPnow", url: "tel:+14806265571" },
    ],
  },
  {
    title: "License and insurance",
    keywords: [
      "license",
      "licensed",
      "licence",
      "practice license",
      "insurance",
      "accept insurance",
      "major insurance",
      "ahcccs",
      "medicare",
      "medicaid",
      "medicare advantage",
      "united health",
      "unitedhealthcare",
      "uhc",
      "cigna",
      "aetna",
      "banner",
      "banner health",
      "health plan",
      "coverage",
      "covered",
    ],
    phrases: [
      "does shiny have license to practice",
      "does shiny has licence to practice",
      "is shiny licensed",
      "do you accept insurance",
      "does telednpnow accept insurance",
      "do you accept ahcccs",
      "do you accept medicare",
      "do you accept medicaid",
      "do you accept medicare advantage",
      "do you accept united health",
      "do you accept cigna",
      "do you accept aetna",
      "do you accept banner health",
    ],
    answer:
      "Shiny Job, DNP, FNP-C is a licensed, board-certified Family Nurse Practitioner. TeleDNPnow may accept major insurance plans; however, insurance participation and coverage can vary by plan, network, service type, and patient eligibility. Please call (480) 626-5571 or email care@telednpnow.org for full insurance information before scheduling, including questions about AHCCCS, Medicare, Medicaid, Medicare Advantage, UnitedHealthcare, Cigna, Aetna, Banner Health, or other plans.",
    links: [
      { label: "Call TeleDNPnow", url: "tel:+14806265571" },
      { label: "Email TeleDNPnow", url: "mailto:care@telednpnow.org" },
    ],
  },
  {
    title: "Self-pay prices",
    keywords: [
      "price",
      "prices",
      "pricing",
      "cost",
      "costs",
      "how much",
      "self pay",
      "self-pay",
      "cash",
      "cash pay",
      "no insurance",
      "without insurance",
      "uninsured",
      "fee",
      "fees",
      "payment",
      "affordable",
      "cheap",
      "credit card",
      "card payment",
      "bluefin",
      "pay",
      "pay online",
      "card",
      "credit",
      "debit",
      "invoice",
      "bill",
      "billing",
      "charge",
      "charges",
    ],
    phrases: [
      "services pricing",
      "service pricing",
      "how much is a visit",
      "how much does it cost",
      "do i need insurance",
      "no insurance",
      "self pay price",
      "cash pay price",
      "how much for sick visit",
      "how much for refill",
      "how much for weight loss",
      "what are your prices",
      "what is the fee",
    ],
    answer:
      "TeleDNPnow offers transparent self-pay prices. Brief sick visit: $40. Initial primary care telehealth visit: $60. Follow-up visit: $40. Weight loss initial consult: $70. Medication refill visit: $30.",
  },
  {
    title: "Weight loss options",
    keywords: [
      "weight loss options",
      "weight loss",
      "obesity",
      "obesity management",
      "medical weight loss",
      "glp-1",
      "semaglutide",
      "tirzepatide",
      "weight management",
      "lose weight",
      "diet",
      "nutrition",
      "lifestyle",
    ],
    phrases: [
      "what options for weight loss",
      "what are weight loss options",
      "do you offer weight loss options",
      "can you help with weight loss options",
      "weight loss treatment options",
      "medical weight loss options",
      "obesity management options",
    ],
    answer:
      "TeleDNPnow offers medical weight loss support for Arizona patients. Weight loss options may include a health history review, medication review, lifestyle and nutrition guidance, activity and habit support, lab discussion when clinically appropriate, follow-up visits, and medication evaluation when appropriate, including GLP-1 options for eligible patients. Treatment is based on each patient's evaluation, medical history, goals, risk factors, and provider assessment. The provider will determine which treatment plan is safe and clinically appropriate.",
    links: [{ label: "Medical Weight Loss Options", url: "/medical_weight_loss_options.html" }],
  },
  {
    title: "Services",
    keywords: [
      "service",
      "services",
      "what do you treat",
      "what can you help",
      "telehealth",
      "telemedicine",
      "virtual care",
      "online care",
      "nurse practitioner",
      "provider",
      "np",
      "dnp",
      "primary care",
      "urgent",
      "quick care",
      "sick visit",
      "women",
      "skin",
      "lab",
      "weight loss",
      "sti",
      "std",
      "chronic",
      "uti",
      "std testing",
      "rash",
      "acne",
      "lab results",
      "blood pressure",
      "diabetes",
      "birth control",
      "menopause",
      "sinus",
      "cold",
      "flu",
      "weight",
      "obesity",
    ],
    phrases: [
      "what services do you offer",
      "what can telednpnow help with",
      "what do you see patients for",
      "do you provide telehealth",
      "can you help with uti",
      "can you help with rash",
      "can you help with weight loss",
      "can you help with medication refill",
      "can you help with lab results",
    ],
    answer:
      "TeleDNPnow offers sick visits, primary care follow-up, chronic care support, medication refill visits, women's health, skin concerns, lab review, sexual health/STI concerns, mental health screening, and medical weight loss management.",
    links: [{ label: "Services", url: "#services" }],
  },
  {
    title: "Common health problems treated",
    keywords: [
      "common",
      "common problems",
      "health problems",
      "conditions",
      "treated",
      "treat",
      "what do you treat",
      "illness",
      "sick",
      "symptoms",
      "health concerns",
      "minor illness",
      "everyday health",
    ],
    phrases: [
      "common health problems treated",
      "what common problems do you treat",
      "what conditions do you treat",
      "what illness can you help with",
      "what symptoms can telehealth help",
    ],
    answer:
      "Common non-emergency concerns TeleDNPnow may help with include cold and flu symptoms, cough, sore throat, sinus symptoms, allergies, UTI symptoms when appropriate, medication refills, high blood pressure follow-up, diabetes follow-up, cholesterol follow-up, asthma follow-up when stable, GERD, lab result review, rash, acne, eczema, skin irritation, women's health concerns, birth control counseling, menopause questions, sexual health/STI concerns, mental health screening, and medical weight loss management. Some symptoms may still require in-person care, urgent care, labs, imaging, or emergency evaluation.",
    links: [
      { label: "Quick Sick Visit Details", url: "/quick-sick-visits.html" },
      { label: "Primary Care Details", url: "/primary_care.html" },
      { label: "Articles", url: "/articles.html" },
    ],
  },
  {
    title: "Common men's health problems treated",
    keywords: [
      "men",
      "mens",
      "men's",
      "male",
      "male health",
      "men health",
      "men's health",
      "erectile dysfunction",
      "ed",
      "premature ejaculation",
      "sexual health",
      "sti",
      "std",
      "urinary",
      "uti",
      "prostate",
      "hair loss",
      "blood pressure",
      "diabetes",
      "cholesterol",
      "weight loss",
      "refill",
      "skin",
      "rash",
    ],
    phrases: [
      "common men's health problems",
      "common mens health problems",
      "men's health problems treated",
      "male health problems treated",
      "what men's health issues do you treat",
    ],
    answer:
      "Common men's health concerns TeleDNPnow may help with by telehealth include erectile dysfunction questions, premature ejaculation concerns, sexual health/STI concerns, urinary symptoms when appropriate, hair loss questions, medication refills, high blood pressure follow-up, diabetes follow-up, cholesterol follow-up, weight loss management, skin concerns, rash, acne, allergies, cold/flu symptoms, and lab result review. Telehealth may not be enough for prostate exams, testicular pain/swelling, severe pelvic pain, chest pain, severe shortness of breath, or emergency symptoms.",
    links: [
      { label: "Sexual Health Details", url: "/sexual_health_sti.html" },
      { label: "Medication Refill Details", url: "/medication_refills.html" },
      { label: "Articles", url: "/articles.html" },
    ],
  },
  {
    title: "Medication refills",
    keywords: [
      "refill",
      "refills",
      "prescription",
      "prescriptions",
      "medication",
      "medications",
      "medicine",
      "non controlled",
      "non-controlled",
      "controlled",
      "controlled substance",
      "opioid",
      "narcotic",
      "pain medication",
      "stimulant",
      "behavioral health medication",
      "inhaler",
      "blood pressure medication",
      "diabetes medication",
      "cholesterol medication",
      "gerd medication",
      "allergy medication",
    ],
    phrases: [
      "can i get a refill",
      "do you refill medication",
      "prescription refill",
      "controlled substances",
      "pain medication",
    ],
    answer:
      "TeleDNPnow can review routine non-controlled medication refill requests when clinically appropriate. TeleDNPnow does not prescribe narcotic pain medications, controlled substances, chronic opioid therapy, or certain behavioral health medications through routine telehealth visits.",
    links: [{ label: "Medication Refill Details", url: "/medication_refills.html" }],
  },
  {
    title: "Controlled substance prescribing policy",
    keywords: [
      "narcotic",
      "narcotics",
      "opioid",
      "opioids",
      "pain pills",
      "pain medication",
      "hydrocodone",
      "oxycodone",
      "percocet",
      "norco",
      "tramadol",
      "benzo",
      "benzos",
      "benzodiazepine",
      "benzodiazepines",
      "xanax",
      "alprazolam",
      "ativan",
      "lorazepam",
      "valium",
      "diazepam",
      "klonopin",
      "clonazepam",
      "blue",
      "blues",
      "stimulant",
      "stimulants",
      "adderall",
      "vyvanse",
      "ritalin",
      "marijuana",
      "marihuana",
      "cannabis",
      "weed",
      "thc",
      "cocaine",
      "coccaine",
      "illegal drug",
      "street drug",
      "controlled substance",
      "controlled substances",
    ],
    phrases: [
      "do they prescribe narcotics",
      "do you prescribe narcotics",
      "do you prescribe benzos",
      "do you prescribe benzodiazepines",
      "can i get xanax",
      "can i get pain pills",
      "can i get opioids",
      "do you prescribe marijuana",
      "do you prescribe cocaine",
      "do you prescribe blue",
      "controlled substances",
    ],
    answer:
      "No. TeleDNPnow does not prescribe narcotics, opioid pain medications, benzodiazepines such as Xanax/Ativan/Valium/Klonopin, stimulants, marijuana/cannabis products, cocaine, illegal drugs, or street drugs. This policy is for patient safety, responsible telehealth care, regulatory compliance, and because these medications/substances require a higher level of evaluation, monitoring, and risk assessment than TeleDNPnow provides through routine telehealth visits.",
    links: [{ label: "Medication Refill Details", url: "/medication_refills.html" }],
  },
  {
    title: "Arizona patients",
    keywords: [
      "arizona",
      "az",
      "state",
      "location",
      "where",
      "serve",
      "service area",
      "florence",
      "phoenix",
      "tucson",
      "mesa",
      "scottsdale",
      "maricopa",
      "pinal",
      "pima",
      "out of state",
      "california",
      "ca",
      "new york",
      "newyork",
      "ny",
      "texas",
      "nevada",
      "other states",
      "another state",
      "all states",
      "outside arizona",
    ],
    phrases: [
      "do you see arizona patients",
      "what state do you serve",
      "can i use telehealth outside arizona",
      "do you treat in new york",
      "do you treat in newyork",
      "do you treat in california",
      "do you treat in other states",
      "are you available in other states",
      "i live in arizona",
    ],
    answer:
      "At present, TeleDNPnow is accepting patients in Arizona only. TeleDNPnow does not currently provide telehealth visits for patients located in New York, California, or other states. Additional states may be added in the future.",
  },
  {
    title: "Emergency warning",
    keywords: [
      "emergency",
      "911",
      "er",
      "emergency room",
      "urgent",
      "urgent care",
      "chest pain",
      "stroke",
      "suicidal",
      "suicide",
      "self harm",
      "severe shortness",
      "severe breathing",
      "shortness of breath",
      "blue lips",
      "fainting",
      "confusion",
      "life threatening",
      "severe allergic reaction",
      "anaphylaxis",
      "severe abdominal pain",
      "uncontrolled bleeding",
    ],
    phrases: [
      "should i call 911",
      "is this an emergency",
      "chest pain",
      "stroke symptoms",
      "severe shortness of breath",
      "suicidal thoughts",
    ],
    answer:
      standardSafetyText,
  },
  {
    title: "Contact",
    keywords: [
      "phone",
      "email",
      "contact",
      "call",
      "number",
      "telephone",
      "reach",
      "message",
      "support",
      "customer service",
      "care@telednpnow.org",
      "480",
      "626",
      "5571",
    ],
    phrases: [
      "what is your phone number",
      "how can i contact",
      "what is your email",
      "call telednpnow",
    ],
    answer:
      "You can contact TeleDNPnow by phone at (480) 626-5571 or by email at care@telednpnow.org.",
    links: [
      { label: "Call", url: "tel:+14806265571" },
      { label: "Email", url: "mailto:care@telednpnow.org" },
    ],
  },
  {
    title: "Working hours",
    keywords: [
      "hours",
      "hour",
      "working hours",
      "business hours",
      "open",
      "opening",
      "opening time",
      "close",
      "closing",
      "closing time",
      "available",
      "availability",
      "today",
      "tomorrow",
      "sunday",
      "monday",
      "tuesday",
      "wednesday",
      "thursday",
      "friday",
      "saturday",
      "weekend",
      "weekday",
      "holiday",
    ],
    phrases: [
      "what time are you open",
      "what are your hours",
      "opening time",
      "business hours",
      "are you open today",
      "are you open on sunday",
      "are you open on saturday",
      "when do you close",
      "when are appointments available",
    ],
    answer: `TeleDNPnow - Telemedicine facility working hours are: ${workingHoursText}. Visits are by appointment and availability may depend on the schedule.`,
    links: [{ label: "Book Visit", url: bookVisitLink }],
  },
  {
    title: "Provider information",
    keywords: [
      "provider",
      "doctor",
      "dr shiny",
      "shiny",
      "shiny job",
      "shinyjob",
      "dr shiny job",
      "dnp",
      "fnp-c",
      "family nurse practitioner",
      "board certified",
      "experience",
      "about",
      "about me",
      "founder",
    ],
    phrases: [
      "who is the provider",
      "who is shiny",
      "who is shiny job",
      "who is dr shiny",
      "who is dr shiny job",
      "who will see me",
      "about dr shiny job",
      "is the provider board certified",
    ],
    answer:
      "Care is provided by Shiny Job, DNP, FNP-C, a board-certified Family Nurse Practitioner and founder of TeleDNPnow with experience in primary care, chronic care, urgent care, correctional healthcare, and telehealth.",
    links: [{ label: "About Me", url: "/about_me.html" }],
  },
  {
    title: "Provider credentials",
    keywords: [
      "physician",
      "doctor",
      "medical doctor",
      "md",
      "do",
      "np",
      "nurse practitioner",
      "family nurse practitioner",
      "fnp",
      "fnp-c",
      "dnp",
      "credential",
      "credentials",
      "license",
      "provider type",
    ],
    phrases: [
      "is shiny a physician",
      "is shiny job a physician",
      "is dr shiny a doctor",
      "is dr shiny job a medical doctor",
      "what is shiny job",
      "what type of provider is shiny",
    ],
    answer:
      "Dr. Shiny Job, DNP, FNP-C is a Family Nurse Practitioner. She is not a physician or medical doctor. DNP means Doctor of Nursing Practice, and FNP-C means board-certified Family Nurse Practitioner.",
    links: [{ label: "About Me", url: "/about_me.html" }],
  },
  {
    title: "Privacy and security",
    keywords: [
      "privacy",
      "hipaa",
      "secure",
      "security",
      "private",
      "confidential",
      "phi",
      "medical information",
      "payment security",
      "bluefin",
      "charmhealth",
      "safe information",
      "safe info",
      "personal information",
      "my information safe",
      "put information",
      "website information",
      "chat information",
    ],
    phrases: [
      "is this secure",
      "is it hipaa compliant",
      "do you store my card",
      "privacy policy",
      "is my information safe",
      "is my information safe if i put the information in your web",
      "is it safe to put my information",
      "can i put my medical information here",
      "should i enter my health information in the chat",
    ],
    answer:
      "Please do not enter private medical details, Social Security numbers, full payment card numbers, or other sensitive personal information into the public website chat. TeleDNPnow uses CharmHealth/CharmTracker as the secure EHR patient portal for registration, visit information, forms, and patient communication. Card numbers are not collected or stored directly on this website. For private health information, please use the secure patient portal or contact TeleDNPnow directly.",
    links: [
      { label: "Privacy Policy", url: "/privacy-policy.html" },
      { label: "Patient Portal", url: patientPortalUrl },
      { label: "Call TeleDNPnow", url: "tel:+14806265571" },
    ],
  },
  {
    title: "Terms and policies",
    keywords: [
      "terms",
      "terms of service",
      "policy",
      "policies",
      "disclaimer",
      "telemedicine disclaimer",
      "limitations",
      "legal",
    ],
    phrases: [
      "terms of service",
      "telehealth disclaimer",
      "telemedicine limitations",
      "what are your policies",
    ],
    answer:
      "TeleDNPnow provides telehealth services for non-emergency medical concerns only. Telehealth has limitations and may not be appropriate for every condition. Some concerns may require in-person care, labs, imaging, specialist referral, urgent care, or emergency care.",
    links: [
      { label: "Terms of Service", url: "/terms-of-service.html" },
      { label: "Privacy Policy", url: "/privacy-policy.html" },
    ],
  },
  ...teleDnpServiceParameters.map((service) => ({
    title: service.service,
    keywords: service.keywords.split(" "),
    phrases: [service.service.toLowerCase()],
    answer: `${service.service} is available through TeleDNPnow when telehealth is clinically appropriate. This information is general only and does not replace a provider visit.`,
    links: [{ label: `${service.service} Details`, url: service.url }],
  })),
];

export const teleDnpArticleLibrary = [
  ["AWV and When Telehealth Can Help", "/article/AWV.html", "annual wellness visit medicare preventive care health risk assessment"],
  ["Asthma and When Telehealth Can Help", "/article/Asthma.html", "asthma wheezing inhaler respiratory breathing"],
  ["COVID-19 and When Telehealth Can Help", "/article/COVID_19.html", "covid covid-19 testing antiviral paxlovid"],
  ["URIs and When Telehealth Can Help", "/article/URIs.html", "uri upper respiratory infection cold cough congestion"],
  ["Allergies and When Telehealth Can Help", "/article/allergies.html", "allergy allergies seasonal allergic rhinitis hives"],
  ["Antibiotics and When Telehealth Can Help", "/article/antibiotics.html", "antibiotics infection bacterial viral resistance"],
  ["Antidepressants and When Telehealth Can Help", "/article/antidepressants.html", "antidepressants ssri depression medication"],
  ["Antihistamines and When Telehealth Can Help", "/article/antihistamines.html", "antihistamine allergy itching hives"],
  ["Antivirals and When Telehealth Can Help", "/article/antivirals.html", "antiviral flu covid herpes"],
  ["Anxiety Medication and When Telehealth Can Help", "/article/anxiety_medication.html", "anxiety medication ssri buspirone"],
  ["Arthritis and When Telehealth Can Help", "/article/arthritis.html", "arthritis joint pain osteoarthritis"],
  ["What Is a Migraine?", "/article/article_migraine.html", "migraine headache aura triggers"],
  ["Back Pain and When Telehealth Can Help", "/article/back_pain.html", "back pain low back strain sciatica"],
  ["Bacterial Vaginosis and When Telehealth Can Help", "/article/bacterial_vaginosis.html", "bacterial vaginosis bv vaginal odor discharge"],
  ["Beta Blockers and When Telehealth Can Help", "/article/beta_blockers.html", "beta blocker blood pressure heart rate metoprolol propranolol"],
  ["Birth Control and When Telehealth Can Help", "/article/birth+control.html", "birth control contraception refill emergency contraception"],
  ["Boils and When Telehealth Can Help", "/article/boils.html", "boil furuncle abscess skin infection"],
  ["Cellulitis and When Telehealth Can Help", "/article/cellulitis.html", "cellulitis red swollen skin infection"],
  ["Chronic Condition Management and When Telehealth Can Help", "/article/chronic_condition_management.html", "chronic condition management diabetes hypertension follow up"],
  ["Cold & Flu and When Telehealth Can Help", "/article/cold_flu.html", "cold flu cough fever sore throat"],
  ["Contact Dermatitis and When Telehealth Can Help", "/article/contact_dermatitis.html", "contact dermatitis poison ivy itchy rash"],
  ["Dandruff and When Telehealth Can Help", "/article/dandruff.html", "dandruff flaky itchy scalp seborrheic dermatitis"],
  ["Diabetes Follow-Up by Telehealth", "/article/diabetes_follow-up_by_telehealth.html", "diabetes follow up a1c glucose blood sugar"],
  ["Diarrhea and When Telehealth Can Help", "/article/diarrhea.html", "diarrhea dehydration stomach illness"],
  ["Eczema and When Telehealth Can Help", "/article/eczema.html", "eczema atopic dermatitis itchy dry skin rash"],
  ["Erectile Dysfunction and When Telehealth Can Help", "/article/erectile_dysfunction.html", "erectile dysfunction ed male sexual health"],
  ["Food Poisoning and When Telehealth Can Help", "/article/food_poisoning.html", "food poisoning vomiting diarrhea nausea"],
  ["Gynecology and When Telehealth Can Help", "/article/gynecology.html", "gynecology women vaginal menstrual birth control sti"],
  ["Hair Loss and When Telehealth Can Help", "/article/hair_loss.html", "hair loss alopecia thinning hair"],
  ["Hemorrhoids and When Telehealth Can Help", "/article/hemorrhoids.html", "hemorrhoids rectal bleeding constipation"],
  ["High Blood Pressure and Home Monitoring", "/article/high_blood_pressure.html", "high blood pressure hypertension home monitoring bp"],
  ["High Blood Pressure Follow-Up", "/article/high_blood_pressure_follow_up.html", "blood pressure follow up hypertension medication"],
  ["Hypertension and When Telehealth Can Help", "/article/hypertension.html", "hypertension high blood pressure bp medication refill"],
  ["Lab Results: What Do They Mean?", "/article/lab_results_what_do_they_mean.html", "lab results abnormal blood work a1c cholesterol thyroid"],
  ["Medication Refills by Telehealth", "/article/medication_refills.html", "medication refill prescription refill telehealth"],
  ["Menopause and When Telehealth Can Help", "/article/menopause.html", "menopause perimenopause hot flashes night sweats"],
  ["Migraine and When Telehealth Can Help", "/article/migraine.html", "migraine headache symptoms medication review"],
  ["Premature Ejaculation and When Telehealth Can Help", "/article/premature_ejaculation.html", "premature ejaculation male sexual health"],
  ["Rash and When Telehealth Can Help", "/article/rash.html", "rash itchy allergic eczema heat rash"],
  ["Rash, Acne, and Skin Concerns", "/article/rash_acne_and_skin_concerns.html", "rash acne skin itching redness irritation"],
  ["Ringworm and When Telehealth Can Help", "/article/ringworm.html", "ringworm tinea fungal rash athlete foot"],
  ["Rosacea and When Telehealth Can Help", "/article/rosacea.html", "rosacea facial redness flare"],
  ["Sinus Infection and When Telehealth Can Help", "/article/sinus_infection.html", "sinus infection sinusitis congestion pressure"],
  ["Skin Infections and When Telehealth Can Help", "/article/skin_infections.html", "skin infection cellulitis infected bite impetigo fungal"],
  ["Strep Throat and When Telehealth Can Help", "/article/strep_throat.html", "strep throat sore throat strep test antibiotics"],
  ["Type 2 Diabetes and When Telehealth Can Help", "/article/type2_diabetes.html", "type 2 diabetes blood sugar a1c medication"],
  ["UTI Symptoms and When Telehealth Can Help", "/article/urinary_tract_infection.html", "uti urinary tract infection burning urination frequency urgency"],
  ["Urinary Tract Infections and When Telehealth Can Help", "/article/urinary_tract_infections.html", "urinary tract infection uti bladder infection"],
  ["Weight Loss Options and GLP-1 Medications", "/article/weight_loss_options_and_GLP-1.html", "weight loss glp-1 semaglutide tirzepatide obesity"],
  ["When to Go to Urgent Care vs Telehealth", "/article/when_to_go_to_urgent_care_vs_telehealth.html", "urgent care vs telehealth emergency warning signs"],
  ["Yeast Infections and When Telehealth Can Help", "/article/yeast_infections.html", "yeast infection vaginal itching candidiasis"],
].map(([title, url, keywords]) => ({ title, url, keywords }));

const normalizeText = (value) =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, " ")
    .replace(/\s+/g, " ")
    .trim();

const toKeywordList = (keywords) => {
  if (Array.isArray(keywords)) return keywords;
  if (typeof keywords === "string") return keywords.split(/\s+/);
  return [];
};

const scoreEntry = (question, entry) => {
  const normalizedQuestion = normalizeText(question);
  const words = normalizedQuestion.split(" ").filter((word) => word.length > 2);
  const keywords = toKeywordList(entry.keywords);
  const haystack = normalizeText(
    `${entry.title} ${keywords.join(" ")} ${(entry.phrases || []).join(" ")} ${entry.answer || ""}`,
  );

  const phraseScore = (entry.phrases || []).reduce((score, phrase) => {
    if (normalizedQuestion.includes(normalizeText(phrase))) return score + 8;
    return score;
  }, 0);

  const keywordScore = keywords.reduce((score, keyword) => {
    const normalizedKeyword = normalizeText(keyword);
    if (!normalizedKeyword) return score;
    if (normalizedQuestion === normalizedKeyword) return score + 8;
    if (normalizedQuestion.includes(normalizedKeyword)) return score + 4;
    return score;
  }, 0);

  const wordScore = words.reduce((score, word) => {
    if (haystack.includes(word)) return score + 1;
    return score;
  }, 0);

  return phraseScore + keywordScore + wordScore;
};

export function findChatKnowledgeAnswer(question) {
  const normalizedQuestion = normalizeText(question);

  if (!normalizedQuestion) return null;

  const emergency = teleDnpQuickAnswers.find((entry) => entry.title === "Emergency warning");
  if (
    [
      "chest pain",
      "stroke",
      "suicidal",
      "suicide",
      "self harm",
      "severe shortness",
      "severe breathing",
      "blue lips",
      "fainting",
      "911",
      "emergency",
    ].some(
      (term) => normalizedQuestion.includes(term),
    )
  ) {
    return { type: "quick", ...emergency };
  }

  const quickMatches = teleDnpQuickAnswers
    .map((entry) => ({ ...entry, score: scoreEntry(question, entry) }))
    .filter((entry) => entry.score > 0)
    .sort((a, b) => b.score - a.score);

  if (quickMatches[0]?.score >= 2) {
    return { type: "quick", ...quickMatches[0] };
  }

  const articleMatches = teleDnpArticleLibrary
    .map((entry) => ({ ...entry, score: scoreEntry(question, entry) }))
    .filter((entry) => entry.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, 3);

  if (articleMatches.length > 0) {
    return {
      type: "articles",
      title: "Helpful TeleDNPnow articles",
      answer:
        "I found TeleDNPnow education articles that may help. These are general education only and do not replace a telehealth visit or emergency care.",
      links: articleMatches.map((article) => ({
        label: article.title.replace(" | TeleDNPnow", ""),
        url: article.url,
      })),
    };
  }

  return null;
}

export const teleDnpKnowledgeContext = [
  `Safety: ${standardSafetyText}`,
  `Working hours: ${workingHoursText}`,
  `Visit prices: ${teleDnpVisitTypes
    .map((visit) => `${visit.name} ${visit.price}`)
    .join("; ")}`,
  ...teleDnpServiceParameters.map(
    (service) => `${service.service}: ${service.keywords}. URL: ${service.url}`,
  ),
  ...teleDnpQuickAnswers.map((entry) => `${entry.title}: ${entry.answer}`),
  ...teleDnpArticleLibrary.map(
    (article) => `${article.title}: ${article.keywords}. URL: ${article.url}`,
  ),
].join("\n");
